/**
 * Empty migration
 */

export const content = `
    -------------------------------------------
    -- $MIGRATION_NAME
    -------------------------------------------

    -------------------------------------------
    -- Generated by: Database Migration
    -- Developer: KeenDev team
    -- Website: https://www.keendev.team
    -- Github: https://github.com/keendev-team
    -------------------------------------------

`;

export const render = (migrationName: string): string => content.replace('$MIGRATION_NAME', migrationName);
